# Generated by Django 6.0.8 on 2026-08-08 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchMenuPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the month', verbose_name='month')),
                ('week_of_month', models.PositiveSmallIntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4'), (5, 'Week 5')], verbose_name='week')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], verbose_name='day')),
                ('dish_name', models.CharField(max_length=200, verbose_name='dish name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('contains_sweet', models.BooleanField(default=False, verbose_name='contains sweet')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('planned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_menus', to=settings.AUTH_USER_MODEL, verbose_name='planned by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'lunch menu plan',
                'verbose_name_plural': 'lunch menu plans',
                'ordering': ['month', 'week_of_month', 'day_of_week'],
                'unique_together': {('tenant', 'month', 'week_of_month', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap Icons class', max_length=50, verbose_name='icon')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'menu category',
                'verbose_name_plural': 'menu categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.menucategory', verbose_name='category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'tea/snack item',
                'verbose_name_plural': 'tea/snack items',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLunchEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('planned_count', models.PositiveIntegerField(default=0, verbose_name='planned token count')),
                ('price_per_token', models.DecimalField(blank=True, decimal_places=2, help_text='Finalized at end of day or month', max_digits=8, null=True, verbose_name='price per token')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked once token issuance starts', verbose_name='locked')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_estimates', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('menu_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='menu.lunchmenuplan', verbose_name='menu plan')),
            ],
            options={
                'verbose_name': 'daily lunch estimate',
                'verbose_name_plural': 'daily lunch estimates',
                'ordering': ['-date'],
                'unique_together': {('tenant', 'date')},
            },
        ),
    ]
