# Generated by Django 6.0.8 on 2026-08-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchmenuplan',
            name='roti_type',
            field=models.CharField(choices=[('roti', 'Standard Roti'), ('naan', 'Tandoori Naan'), ('roghni', 'Roghni Naan'), ('na', 'N/A (Rice / No Roti)')], default='roti', help_text='Type of Roti/Naan served with this lunch menu (or N/A for Rice dishes)', max_length=20, verbose_name='roti type'),
        ),
    ]
