# Generated by Django 6.0.8 on 2026-08-09 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_lunchmenuplan_roti_type'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylunchestimate',
            name='actual_extra_roti_issued',
            field=models.PositiveIntegerField(default=0, verbose_name='actual extra roti issued'),
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='actual_extra_sweet_issued',
            field=models.PositiveIntegerField(default=0, verbose_name='actual extra sweet issued'),
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='actual_tokens_issued',
            field=models.PositiveIntegerField(default=0, verbose_name='actual tokens issued'),
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Can be positive or negative amount', max_digits=10, verbose_name='adjustment amount'),
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='dish_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='dish name'),
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='estimated_extra_roti',
            field=models.PositiveIntegerField(default=0, verbose_name='estimated extra roti count'),
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='estimated_extra_sweet',
            field=models.PositiveIntegerField(default=0, verbose_name='estimated extra sweet count'),
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='roti_type',
            field=models.CharField(choices=[('roti', 'Standard Roti'), ('naan', 'Tandoori Naan'), ('roghni', 'Roghni Naan'), ('na', 'N/A (Rice / No Roti)')], default='roti', max_length=20, verbose_name='roti type'),
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='roti_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='roti unit price'),
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='sweet_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='sweet unit price'),
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='token_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='net token expense'),
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total daily expense'),
        ),
        migrations.AlterField(
            model_name='dailylunchestimate',
            name='price_per_token',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated: Net Token Expense / Actual Tokens Issued', max_digits=8, verbose_name='token unit cost'),
        ),
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='cook name')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'cook',
                'verbose_name_plural': 'cooks',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entries', to='menu.cook', verbose_name='cook'),
        ),
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='sweet name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='fixed price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'sweet',
                'verbose_name_plural': 'sweets',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='sweet',
            field=models.ForeignKey(blank=True, help_text='Select NA / leave empty if no sweet included', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entries', to='menu.sweet', verbose_name='sweet'),
        ),
        migrations.CreateModel(
            name='RotiPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roti_type', models.CharField(choices=[('roti', 'Standard Roti'), ('naan', 'Tandoori Naan'), ('roghni', 'Roghni Naan'), ('na', 'N/A (Rice / No Roti)')], max_length=20, verbose_name='roti type')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price per unit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'roti price setup',
                'verbose_name_plural': 'roti price setup',
                'unique_together': {('tenant', 'roti_type')},
            },
        ),
    ]
