# Generated by Django 6.0.8 on 2026-08-09 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dailylunchestimate_actual_extra_roti_issued_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotiprice',
            options={'ordering': ['name'], 'verbose_name': 'roti price setup', 'verbose_name_plural': 'roti price setup'},
        ),
        migrations.AlterUniqueTogether(
            name='rotiprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailylunchestimate',
            name='roti_price_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entries', to='menu.rotiprice', verbose_name='roti / naan selection'),
        ),
        migrations.AddField(
            model_name='rotiprice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='rotiprice',
            name='name',
            field=models.CharField(default='Standard Roti', max_length=100, verbose_name='roti / naan name'),
        ),
        migrations.AlterField(
            model_name='dailylunchestimate',
            name='roti_type',
            field=models.CharField(default='roti', max_length=50, verbose_name='roti type'),
        ),
        migrations.AlterField(
            model_name='rotiprice',
            name='roti_type',
            field=models.CharField(blank=True, default='roti', max_length=50, verbose_name='roti type code'),
        ),
    ]
