# Generated by Django 6.0.8 on 2026-08-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_rotiprice_options_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunchmenuplan',
            options={'ordering': ['week_of_month', 'day_of_week'], 'verbose_name': 'master lunch menu plan', 'verbose_name_plural': 'master lunch menu plans'},
        ),
        migrations.AlterUniqueTogether(
            name='lunchmenuplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lunchmenuplan',
            name='cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_plans', to='menu.cook', verbose_name='default cook'),
        ),
        migrations.AddField(
            model_name='lunchmenuplan',
            name='roti_price_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_plans', to='menu.rotiprice', verbose_name='roti / naan selection'),
        ),
        migrations.AddField(
            model_name='lunchmenuplan',
            name='sweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_plans', to='menu.sweet', verbose_name='default sweet'),
        ),
        migrations.AlterField(
            model_name='lunchmenuplan',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='lunchmenuplan',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='lunchmenuplan',
            name='month',
            field=models.DateField(blank=True, help_text='Optional month reference', null=True, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='lunchmenuplan',
            name='roti_type',
            field=models.CharField(blank=True, choices=[('roti', 'Standard Roti'), ('naan', 'Tandoori Naan'), ('roghni', 'Roghni Naan'), ('na', 'N/A (Rice / No Roti)')], default='roti', max_length=50, verbose_name='roti type'),
        ),
        migrations.AlterUniqueTogether(
            name='lunchmenuplan',
            unique_together={('tenant', 'week_of_month', 'day_of_week')},
        ),
    ]
