# Generated by Django 6.0.8 on 2026-08-08 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the billing month', verbose_name='month')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misc_charges', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'misc charge',
                'verbose_name_plural': 'misc charges',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('line_items', models.JSONField(default=list, help_text='List of {description, quantity, unit_price, total} dicts', verbose_name='line items')),
                ('token_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='token total')),
                ('extra_roti_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='extra roti total')),
                ('extra_sweet_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='extra sweet total')),
                ('misc_charges_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='misc charges')),
                ('security_deposit_pending', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='security deposit pending')),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, help_text='Unpaid balance from previous month', max_digits=10, verbose_name='previous balance carryforward')),
                ('adjustment_total', models.DecimalField(decimal_places=2, default=0, help_text='Pro-rata month-end adjustment', max_digits=10, verbose_name='adjustment total')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('published', 'Published'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bills', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_bills', to='employees.employee', verbose_name='employee')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bills', to=settings.AUTH_USER_MODEL, verbose_name='generated by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bills', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'monthly bill',
                'verbose_name_plural': 'monthly bills',
                'ordering': ['-period_start', 'employee'],
                'unique_together': {('tenant', 'employee', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount paid')),
                ('payment_date', models.DateField(verbose_name='payment date')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online')], default='cash', max_length=20, verbose_name='method')),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, help_text="Auto-carried to next month's bill if > 0", max_digits=10, verbose_name='remaining balance')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='reference')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.monthlybill', verbose_name='bill')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='received by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
