# Generated by Django 6.0.8 on 2026-08-09 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='total_extra_roti_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='total extra roti qty'),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='total_extra_sweet_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='total extra sweet qty'),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='total_token_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='total token qty'),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='MonthlyBillRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bill_runs', to=settings.AUTH_USER_MODEL, verbose_name='generated by')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_bill_runs', to=settings.AUTH_USER_MODEL, verbose_name='published by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'monthly bill run',
                'verbose_name_plural': 'monthly bill runs',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'period_start'), name='unique_bill_run_per_tenant_month')],
            },
        ),
    ]
