"""Billing App – Models."""
import decimal
from django.db import models
from django.utils.translation import gettext_lazy as _
from apps.core.models import TenantModel


class BillStatus(models.TextChoices):
    UNPAID = "unpaid", _("Unpaid")
    PARTIALLY_PAID = "partially_paid", _("Partially Paid")
    PAID = "paid", _("Paid")


class MonthlyBillRunStatus(models.TextChoices):
    DRAFT = "draft", _("Draft")
    PUBLISHED = "published", _("Published")


class MonthlyBillRun(TenantModel):
    """
    Tracks a monthly bill generation batch entry (e.g. July 2026).
    Manages month-level status (Draft vs Published), publishing, and notification triggers.
    """
    period_start = models.DateField(_("period start"))
    period_end = models.DateField(_("period end"))
    status = models.CharField(
        _("status"),
        max_length=20,
        choices=MonthlyBillRunStatus.choices,
        default=MonthlyBillRunStatus.DRAFT,
        db_index=True,
    )
    published_at = models.DateTimeField(_("published at"), null=True, blank=True)
    published_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="published_bill_runs",
        verbose_name=_("published by"),
    )
    generated_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        related_name="generated_bill_runs",
        verbose_name=_("generated by"),
    )

    class Meta:
        verbose_name = _("monthly bill run")
        verbose_name_plural = _("monthly bill runs")
        ordering = ["-period_start"]
        constraints = [
            models.UniqueConstraint(
                fields=["tenant", "period_start"],
                name="unique_bill_run_per_tenant_month",
            )
        ]

    def __str__(self):
        return f"{self.period_start.strftime('%B %Y')} — {self.get_status_display()}"


class MiscCharge(TenantModel):
    """
    Miscellaneous monthly charge applied to qualifying members.
    Rule (spec §4): only applied to members with ≥1 token AND not
    (pending-amount with roti-only membership).
    """
    month = models.DateField(_("month"), help_text=_("First day of the billing month"))
    amount = models.DecimalField(_("amount"), max_digits=10, decimal_places=2)
    description = models.CharField(_("description"), max_length=300)
    created_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        related_name="misc_charges",
        verbose_name=_("created by"),
    )

    class Meta:
        verbose_name = _("misc charge")
        verbose_name_plural = _("misc charges")
        ordering = ["-month"]

    def __str__(self):
        return f"{self.month.strftime('%b %Y')} — {self.amount} ({self.description})"


class MonthlyBill(TenantModel):
    """
    Monthly bill for a single employee.
    Status choices: Unpaid, Partially Paid, Paid.
    """
    employee = models.ForeignKey(
        "employees.Employee",
        on_delete=models.PROTECT,
        related_name="monthly_bills",
        verbose_name=_("employee"),
    )
    period_start = models.DateField(_("period start"))
    period_end = models.DateField(_("period end"))

    # Line items (stored as JSON for flexibility)
    line_items = models.JSONField(
        _("line items"),
        default=list,
        help_text=_("List of {description, quantity, unit_price, total} dicts"),
    )

    # Quantities
    total_token_qty = models.PositiveIntegerField(_("total token qty"), default=0)
    total_extra_roti_qty = models.PositiveIntegerField(_("total extra roti qty"), default=0)
    total_extra_sweet_qty = models.PositiveIntegerField(_("total extra sweet qty"), default=0)

    # Totals
    token_total = models.DecimalField(_("token total"), max_digits=10, decimal_places=2, default=0)
    extra_roti_total = models.DecimalField(_("extra roti total"), max_digits=10, decimal_places=2, default=0)
    extra_sweet_total = models.DecimalField(_("extra sweet total"), max_digits=10, decimal_places=2, default=0)
    misc_charges_total = models.DecimalField(_("misc charges"), max_digits=10, decimal_places=2, default=0)
    security_deposit_pending = models.DecimalField(
        _("security deposit pending"),
        max_digits=10,
        decimal_places=2,
        default=0,
    )
    previous_balance = models.DecimalField(
        _("previous balance carryforward"),
        max_digits=10,
        decimal_places=2,
        default=0,
        help_text=_("Unpaid balance from previous month"),
    )
    adjustment_total = models.DecimalField(
        _("adjustment total"),
        max_digits=10,
        decimal_places=2,
        default=0,
        help_text=_("Pro-rata month-end adjustment"),
    )
    subtotal = models.DecimalField(_("subtotal"), max_digits=10, decimal_places=2, default=0)
    total = models.DecimalField(_("total"), max_digits=10, decimal_places=2, default=0)

    # Status: Unpaid, Partially Paid, Paid
    status = models.CharField(
        _("status"),
        max_length=20,
        choices=BillStatus.choices,
        default=BillStatus.UNPAID,
        db_index=True,
    )
    generated_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        related_name="generated_bills",
        verbose_name=_("generated by"),
    )
    reviewed_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reviewed_bills",
        verbose_name=_("reviewed by"),
    )
    approved_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="approved_bills",
        verbose_name=_("approved by"),
    )
    published_at = models.DateTimeField(_("published at"), null=True, blank=True)

    class Meta:
        verbose_name = _("monthly bill")
        verbose_name_plural = _("monthly bills")
        ordering = ["-period_start", "employee"]
        unique_together = [["tenant", "employee", "period_start"]]

    def __str__(self):
        return f"{self.employee} | {self.period_start.strftime('%b %Y')} | PKR {self.total} [{self.get_status_display()}]"

    def calculate_totals(self):
        """Recompute all total fields from line_items."""
        self.subtotal = (
            self.token_total
            + self.extra_roti_total
            + self.extra_sweet_total
            + self.misc_charges_total
            + self.adjustment_total
        )
        self.total = (
            self.subtotal
            + self.security_deposit_pending
            + self.previous_balance
        )
        return self.total

    @property
    def summary_line_items(self):
        """
        Returns a clean, structured list of line items including Token, Extra Roti,
        Extra Sweet, and Misc charges with quantities and rates.
        """
        if self.line_items and len(self.line_items) > 0:
            return self.line_items

        items = []

        # 1. Lunch Tokens
        if self.token_total > 0:
            token_count = self.employee.lunch_tokens.filter(
                date__range=(self.period_start, self.period_end),
                status="issued"
            ).count() or 1
            unit_rate = (self.token_total / decimal.Decimal(token_count)).quantize(decimal.Decimal("0.01")) if token_count else self.token_total
            items.append({
                "description": f"Lunch Tokens ({token_count} Days)",
                "quantity": token_count,
                "unit_price": f"{unit_rate:,.2f}",
                "total": f"{self.token_total:,.2f}",
            })

        # 2. Extra Roti
        if self.extra_roti_total > 0:
            roti_qty = int(self.extra_roti_total // decimal.Decimal("15.00")) or 1
            items.append({
                "description": "Extra Roti Issued",
                "quantity": roti_qty,
                "unit_price": "15.00",
                "total": f"{self.extra_roti_total:,.2f}",
            })

        # 3. Extra Sweet
        if self.extra_sweet_total > 0:
            sweet_qty = int(self.extra_sweet_total // decimal.Decimal("35.00")) or 1
            items.append({
                "description": "Extra Sweet Issued",
                "quantity": sweet_qty,
                "unit_price": "35.00",
                "total": f"{self.extra_sweet_total:,.2f}",
            })

        # 4. Misc Charges
        if self.misc_charges_total > 0:
            items.append({
                "description": "Cafeteria Maintenance & Misc Charges",
                "quantity": 1,
                "unit_price": f"{self.misc_charges_total:,.2f}",
                "total": f"{self.misc_charges_total:,.2f}",
            })

        return items

    def can_transition_to(self, new_status, user):
        """Enforce valid workflow transitions."""
        valid_transitions = {
            BillStatus.DRAFT: [BillStatus.REVIEWED],
            BillStatus.REVIEWED: [BillStatus.APPROVED, BillStatus.DRAFT],
            BillStatus.APPROVED: [BillStatus.PUBLISHED],
            BillStatus.PUBLISHED: [BillStatus.PAID, BillStatus.PARTIALLY_PAID],
        }
        return new_status in valid_transitions.get(self.status, [])


class Payment(TenantModel):
    """Payment record against a monthly bill. Partial payments are supported."""
    bill = models.ForeignKey(
        MonthlyBill,
        on_delete=models.CASCADE,
        related_name="payments",
        verbose_name=_("bill"),
    )
    amount_paid = models.DecimalField(_("amount paid"), max_digits=10, decimal_places=2)
    payment_date = models.DateField(_("payment date"))
    method = models.CharField(
        _("method"),
        max_length=20,
        choices=[
            ("cash", _("Cash")),
            ("bank", _("Bank Transfer")),
            ("cheque", _("Cheque")),
            ("online", _("Online")),
        ],
        default="cash",
    )
    received_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        related_name="received_payments",
        verbose_name=_("received by"),
    )
    remaining_balance = models.DecimalField(
        _("remaining balance"),
        max_digits=10,
        decimal_places=2,
        default=0,
        help_text=_("Auto-carried to next month's bill if > 0"),
    )
    reference = models.CharField(_("reference"), max_length=100, blank=True)
    note = models.TextField(_("note"), blank=True)

    class Meta:
        verbose_name = _("payment")
        verbose_name_plural = _("payments")
        ordering = ["-payment_date"]

    def __str__(self):
        return f"{self.bill.employee} | PKR {self.amount_paid} on {self.payment_date}"
