# Generated by Django 6.0.8 on 2026-08-08 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('menu', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('token_number', models.PositiveSmallIntegerField(help_text='1–3 per day', verbose_name='token number')),
                ('issue_time', models.DateTimeField(auto_now_add=True, verbose_name='issue time')),
                ('extra_roti_qty', models.PositiveSmallIntegerField(default=0, verbose_name='extra roti qty')),
                ('extra_sweet_qty', models.PositiveSmallIntegerField(default=0, verbose_name='extra sweet qty')),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled')], db_index=True, default='issued', max_length=20, verbose_name='status')),
                ('price_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated price at issuance; hidden from employee until billed', max_digits=8, null=True, verbose_name='price snapshot')),
                ('adjustment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Pro-rata adjustment applied at billing time', max_digits=8, null=True, verbose_name='month-end adjustment')),
                ('roti_override', models.BooleanField(default=False, help_text='True if staff overrode the Roti-Open lock for this token', verbose_name='roti-open override')),
                ('daily_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='menu.dailylunchestimate', verbose_name='daily estimate')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_tokens', to='employees.employee', verbose_name='employee')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tokens', to=settings.AUTH_USER_MODEL, verbose_name='issued by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'lunch token',
                'verbose_name_plural': 'lunch tokens',
                'ordering': ['-date', '-issue_time'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'date', 'employee', 'token_number'), name='unique_token_per_employee_per_day')],
            },
        ),
    ]
