# Generated by Django 6.0.8 on 2026-08-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchtoken',
            name='token_qty',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of tokens issued in this transaction (1–5)', verbose_name='token quantity'),
        ),
        migrations.AlterField(
            model_name='lunchtoken',
            name='token_number',
            field=models.PositiveSmallIntegerField(help_text='Sequence number for today', verbose_name='token number'),
        ),
    ]
