# Generated by Django 6.0.8 on 2026-08-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_lunchtoken_token_qty_alter_lunchtoken_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchtoken',
            name='is_retroactive',
            field=models.BooleanField(default=False, help_text='True if retroactively charged via daily closing report', verbose_name='is retroactive charge'),
        ),
    ]
