# Generated by Django 6.0.8 on 2026-08-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('short_title', models.CharField(max_length=50, verbose_name='short title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/', verbose_name='logo')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='contact phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('currency', models.CharField(default='PKR', max_length=10, verbose_name='currency')),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=50, verbose_name='timezone')),
                ('max_tokens_per_day', models.PositiveSmallIntegerField(default=3, help_text='Maximum lunch tokens an employee can issue per day', verbose_name='max tokens per day')),
                ('schema_name', models.CharField(default='public', help_text='PostgreSQL schema name. Set automatically from slug.', max_length=100, unique=True, verbose_name='schema name')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='paid until')),
                ('on_trial', models.BooleanField(default=True, verbose_name='on trial')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True, verbose_name='domain')),
                ('is_primary', models.BooleanField(default=True, verbose_name='primary')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domains',
                'ordering': ['domain'],
            },
        ),
    ]
