# Generated by Django 6.0.8 on 2026-08-08 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100, verbose_name='action')),
                ('model_name', models.CharField(max_length=100, verbose_name='model')),
                ('object_id', models.CharField(max_length=100, verbose_name='object ID')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='before')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='after')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='code')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_id', models.CharField(blank=True, max_length=50, verbose_name='system ID')),
                ('pno', models.CharField(blank=True, max_length=50, verbose_name='P-No')),
                ('register_number', models.CharField(blank=True, max_length=50, verbose_name='register number')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='mobile')),
                ('telephone_extension', models.CharField(blank=True, max_length=20, verbose_name='telephone extension')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, verbose_name='gender')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='designation')),
                ('category', models.CharField(choices=[('officer', 'Officer'), ('staff', 'Staff')], default='staff', max_length=20, verbose_name='category')),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='date joined')),
                ('membership_status', models.BooleanField(default=False, help_text='Is this employee a cafe member?', verbose_name='membership active')),
                ('membership_type', models.CharField(choices=[('full_open', 'Full Open'), ('roti_open', 'Roti Open'), ('temp_close', 'Temp Close')], default='temp_close', max_length=20, verbose_name='membership type')),
                ('security_deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='security deposit paid')),
                ('security_deposit_pending', models.DecimalField(decimal_places=2, default=0, help_text='Auto-appended to next monthly bill if > 0', max_digits=10, verbose_name='security deposit pending')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department', verbose_name='department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='user account')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['full_name'],
                'unique_together': {('tenant', 'pno'), ('tenant', 'register_number')},
            },
        ),
    ]
