# Generated by Django 6.0.8 on 2026-08-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='membership_type',
            field=models.CharField(choices=[('full_open', 'Full Open'), ('roti_open', 'Roti Open'), ('temp_close', 'Temp Close'), ('not_member', 'Not Member')], default='temp_close', max_length=20, verbose_name='membership type'),
        ),
    ]
