# Generated by Django 6.0.8 on 2026-08-08 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenOpenCloseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('open', 'Open (Resume Membership)'), ('close', 'Close (Pause Membership)')], max_length=10, verbose_name='type')),
                ('date_range_start', models.DateField(verbose_name='from date')),
                ('date_range_end', models.DateField(verbose_name='to date')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acknowledged at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_requests', to=settings.AUTH_USER_MODEL, verbose_name='acknowledged by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_close_requests', to='employees.employee', verbose_name='employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'open/close request',
                'verbose_name_plural': 'open/close requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
