# Generated by Django 6.0.8 on 2026-08-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenopencloserequest',
            name='requested_token_qty',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of tokens requested for open request (1-5)', verbose_name='requested token quantity'),
        ),
    ]
