# Generated by Django 6.0.8 on 2026-08-08 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('menu', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaItemSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='unit price')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount paid')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Payment'), ('account', 'Account Deduction')], default='cash', max_length=20, verbose_name='payment method')),
                ('is_walk_in', models.BooleanField(default=False, help_text='True if buyer is not an employee', verbose_name='walk-in customer')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tea_purchases', to='employees.employee', verbose_name='buyer (employee)')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to=settings.AUTH_USER_MODEL, verbose_name='issued by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='menu.teaitem', verbose_name='item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'tea/snack sale',
                'verbose_name_plural': 'tea/snack sales',
                'ordering': ['-created_at'],
            },
        ),
    ]
