# Generated by Django 6.0.8 on 2026-08-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaitemsale',
            name='order_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Unique reference grouping items of a single checkout order', max_length=50, verbose_name='order reference'),
        ),
    ]
